site_name: GenomeNet Documentation
site_url: http://genomenet.de/about #this is the main site!
site_description: GenomeNet Documentation 
site_author: Philipp Münch

repo_url: https://github.com/genomenet/about
repo_name: 'GitHub Home'

theme:
  name: material

nav:
  - Home: 'index.md'
