site_name: GenomeNet
site_url: https://genomenet.de/
site_description: Deep neural nets for genomic modelling
site_author: Philipp Münch

repo_url: https://github.com/genomenet/genomenet.de
repo_name: genomenet/genomenet.de

theme:
  name: material
  include_search_page: false   # Don't include MkDocs' JavaScript
  search_index_only: true
  language: en
  features:
    - tabs
  palette:
    primary: black
    accent: black
  font:
    text: Roboto Mono
    code: Roboto Mono
  logo: images/logo_simple.png

copyright: "Copyright &copy; 2020 GenomeNet Author(s)"

markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.attr_list
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Page tree
nav:
  - About: index.md
  - Progress: 
      - Status: progress.md
  - Resources:
    - deepG:
      - Installation: ./deepG/installation.md
      - Getting started: ./deepG/getting-started.md
      - Build functions: ./deepG/build.md
      - Scan functions: ./deepG/scan.md
      - Examples: ./deepG/examples.md
      - License: ./deepG/license.md
