site_name: GenomeNet
site_url: https://genomenet.de/
site_description: Deep neural nets for genomic modelling
site_author: Philipp Münch

repo_url: https://github.com/genomenet/genomenet.de
repo_name: 'genomenet/genomenet.de'

theme:
  name: material
  include_search_page: false   # Don't include MkDocs' JavaScript
  search_index_only: true
  language: en
  feature:
    tabs: true
  palette:
    primary: 'grey'
    accent: 'black'
  font:
    text: Robo
    code: Robo Mono
  logo: 'images/logo_simple.png'
docs_dir: docs
copyright: 'Copyright &copy; 2020 Philipp C. Münch'

markdown_extensions:
  - codehilite
      guess_lang: false
  - admonition
  - footnotes
  - pymdownx.tabbed
  - pymdownx.tilde
  - toc:
      permalink: true

nav:
  - Introduction: 'index.md'
  - Progress: 'progress.md'
  - DeepG:
    - 'Installation': 'deepg/installation.md'
    - 'Getting started': 'deepg/getting-started.md'
    - 'Examples': 'deepg/examples.md'
  - About:
    - 'License': 'license.md'
