site_name: GenomeNet Documentation
site_url: http://genomenet.de/about #this is the main site!
site_description: GenomeNet Documentation 
site_author: Philipp Münch

repo_url: https://github.com/genomenet/about
repo_name: 'About'

theme:
  name: material
  include_search_page: false   # Don't include MkDocs' JavaScript
  search_index_only: true
  language: en
  feature:
    tabs: false
  palette:
    primary: indigo
    accent: indigo
  font:
    text: Roboto
    code: Roboto Mono

nav:
  - Home: 'index.md'
