site_name: GenomeNet
site_url: https://genomenet.netlify.app/ #this is the main site!
site_description: Deep neural nets for genomic modelling
site_author: Philipp Münch

repo_url: https://github.com/genomenet/genomenet.de
repo_name: 'genomenet.de'

theme:
  name: material
  include_search_page: false   # Don't include MkDocs' JavaScript
  search_index_only: true
  language: en
  feature:
    tabs: true
  palette:
    primary: grey
    accent: green
  font:
    text: Robo
    code: Robo Mono
  logo: 'https://github.com/GenomeNet/genomenet.de/blob/master/images/logo.png?raw=true'

nav:
  - Home: index.md
  - Project overview: project-overview.md
  - DeepG:
    - Installation: deepg/installation.md
    - Getting started: deepg/getting-started.md
    - Examples: deepg/examples.md
  - Contributing: contributing.md
  - License: license.md
