site_name: GenomeNet
site_url: http://www.genomenet.de #this is the main site!
site_description: Deep neural nets for genomic modelling
site_author: Philipp Münch

repo_url: https://github.com/genomenet/genomenet.de
repo_name: 'genomenet.de'

theme:
  name: material
  include_search_page: false   # Don't include MkDocs' JavaScript
  search_index_only: true
  language: en
  feature:
    tabs: false
  palette:
    primary: grey
    accent: green
  font:
    text: Roboto
    code: Roboto Mono
  logo: 'images/logo.png'

nav:
  - Home: 'index.md'
  - deepG: 'deepG/index.md'
