site_name: GenomeNet
site_url: https://genomenet.de/
site_description: Deep neural nets for genomic modelling
site_author: Philipp Münch

repo_url: https://github.com/genomenet/genomenet.de
repo_name: genomenet/genomenet.de

theme:
  name: material
  include_search_page: false   # Don't include MkDocs' JavaScript
  search_index_only: true
  language: en
  feature:
    tabs: true
  palette:
    primary: grey
    accent: red
  font:
    text: Robo Mono
    code: Robo Mono
  logo: images/logo_black.png

copyright: "Copyright &copy; 2020 GenomeNet Author(s)"

markdown_extensions:
  - codehilite
  - admonition
  - footnotes
  - toc:
      permalink: true

# Page tree
nav:
  - Introduction: index.md
  - Progress: progress.md
  - deepG:
    - Installation: ./deepG/installation.md
    - Getting started: ./deepG/getting-started.md
    - Build functions: ./deepG/build.md
    - Scan functions: ./deepG/scan.md
    - Examples: ./deepG/examples.md
  - About:
    - License: license.md
